# Generated by Django 3.0.2 on 2020-04-01 05:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='dadosmodels',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('paymentMethod', models.CharField(default='', max_length=100)),
                ('yearsTopay', models.FloatField(default=0)),
                ('entry', models.FloatField(default=0)),
                ('usuario', models.CharField(default='', max_length=100)),
                ('energyconsume', models.FloatField(default=0)),
                ('radiation1', models.CharField(default='', max_length=100)),
                ('radiation2', models.FloatField(default=0)),
                ('radiation3', models.FloatField(default=0)),
                ('pricekwh', models.FloatField(default=0)),
                ('economy', models.FloatField(default=0)),
                ('painelpower', models.FloatField(default=0)),
                ('panelprice1', models.CharField(default='', max_length=100)),
                ('panelprice2', models.FloatField(default=0)),
                ('panelprice3', models.FloatField(default=0)),
                ('priceinverters1', models.CharField(default='', max_length=100)),
                ('priceinverters2', models.FloatField(default=0)),
                ('priceinverters3', models.FloatField(default=0)),
                ('pricestringbox', models.FloatField(default=0)),
                ('priceproject', models.FloatField(default=0)),
                ('pricewiring', models.FloatField(default=0)),
                ('pricess', models.FloatField(default=0)),
                ('pricelabor', models.FloatField(default=0)),
                ('maintenance', models.FloatField(default=0)),
                ('inflation', models.FloatField(default=0)),
                ('ccp1', models.CharField(default='', max_length=100)),
                ('ccp2', models.FloatField(default=0)),
                ('ccp3', models.FloatField(default=0)),
                ('cct1', models.CharField(default='', max_length=100)),
                ('cct2', models.FloatField(default=0)),
                ('cct3', models.FloatField(default=0)),
                ('pccp', models.FloatField(default=0)),
                ('pcct', models.FloatField(default=0)),
                ('plifespan1', models.CharField(default='', max_length=100)),
                ('plifespan2', models.FloatField(default=0)),
                ('plifespan3', models.FloatField(default=0)),
                ('plifespan4', models.FloatField(default=0)),
                ('plifespan5', models.FloatField(default=0)),
                ('plifespan6', models.FloatField(default=0)),
                ('plifespan7', models.FloatField(default=0)),
                ('ilifespan1', models.CharField(default='', max_length=100)),
                ('ilifespan2', models.FloatField(default=0)),
                ('ilifespan3', models.FloatField(default=0)),
                ('ilifespan4', models.FloatField(default=0)),
                ('ilifespan5', models.FloatField(default=0)),
                ('ilifespan6', models.FloatField(default=0)),
                ('ilifespan7', models.FloatField(default=0)),
                ('preduction', models.FloatField(default=0)),
                ('projeto', models.CharField(default='', max_length=100)),
                ('maintenance1', models.CharField(default='', max_length=100)),
                ('maintenance2', models.FloatField(default=0)),
                ('maintenance3', models.FloatField(default=0)),
                ('energy_production_tax', models.FloatField(default=0)),
                ('depreciation_years_inverters', models.FloatField(default=0)),
                ('depreciation_years_painels', models.FloatField(default=0)),
                ('person_or_business_or_sellenergy', models.CharField(default='', max_length=100)),
                ('incometax', models.FloatField(default=0)),
                ('sim_year', models.FloatField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='testmodels',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('test1', models.CharField(default='', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='uuprofile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(default='', max_length=100)),
                ('country', models.CharField(default='', max_length=100)),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
