# Generated by Django 2.0 on 2020-05-18 04:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0002_dadosmodels_dictstringresult'),
    ]

    operations = [
        migrations.AddField(
            model_name='dadosmodels',
            name='clientShare',
            field=models.TextField(default=''),
        ),
    ]
