# Generated by Django 2.0 on 2020-05-28 02:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0003_dadosmodels_clientshare'),
    ]

    operations = [
        migrations.AddField(
            model_name='dadosmodels',
            name='npanel',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='dadosmodels',
            name='sellOrComp',
            field=models.TextField(default=''),
        ),
    ]
